import type { Metadata } from "next";

import { Toaster } from "@/components/ui/sonner";
import AuthSessionProvider from "@/providers/auth-session-provider";
import { ReactQueryProviderClient } from "@/providers/react-query-provider-client";
import { ThemeProviderClient } from "@/providers/theme-provider";
import { Inter } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <ThemeProviderClient>
          <ReactQueryProviderClient>
            <AuthSessionProvider />
            <NuqsAdapter>{children}</NuqsAdapter>
            <Toaster />
          </ReactQueryProviderClient>
        </ThemeProviderClient>
      </body>
    </html>
  );
}
